# State
EMPTY = -1
# USER_FIRST_TRY = 0
# USER_SECOND_TRY = 1
USER_FINAL_QUESTION = 2
# USER_FINAL_QUESTION_SECOND_TRY = 3
USER_EMAIL_NOT_FOUND = 4
USER_ENTER_EMAIL = 5
USER_PROMO_IDENTIFIER = 6
USER_USE_PROMO = 7
USER_CHANGE_EMAIL = 8
